name: abdelrhman
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  bubble_bottom_bar: ^1.2.0
  scroll_app_bar: ^1.0.2
  english_words: ^3.1.3
  sticky_headers: ^0.1.8+1
  font_awesome_flutter: ^8.10.0
  flutter_vector_icons: ^0.2.1
  video_player: ^0.10.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  chewie: ^0.9.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - image/Abdo.jpg
    - image/abdo1.jpg
    - image/abdo2.jpg
    - image/flutter.jpg
    - image/onfire.jpg
    - image/MSP.jpg
    - image/fff.jpg
    - image/coli.jpg
    - image/co2.jfif
    - image/co1.jpg
    - image/co.jfif
    - image/inter.jpg
    - image/view.jpg
    - image/fe.jpg
    - image/fa.jpg
    - image/face.jpg
    - image/cc.jpg
    - image/es.jpg
    - image/ma.jpg
    - image/mi.jpg
    - image/mira.jpg
    - image/mm.jpg
    - image/mo.jpg
    - image/aaa.jpg
    - image/faa.jpg
    - image/bb.jpg
    - image/MS.jpg
    - image/El.jpg
    - image/ch.jpg
    - image/fh.jpg
    - image/sh.jpg
    - image/ah.jpg
    - image/ss.jpg
    - image/sa.jpg
    - image/sb.jpg
    - image/qq.jpg
    - image/qw.jpg
    - image/qe.jpg
    - image/qr.jpg
    - image/a.jpg
    - image/b.jpeg
    - image/c.jpeg
    - image/d.jpg
    - image/e.jpg
    - image/f.jpg
    - image/g.jpg
    - image/h.jpg
    - image/i.jpeg
    - image/j.jpg
    - image/x.jpg
    - video/momo.mp4


  fonts:
    - family: pacifico
      fonts:
        - asset: fonts/pacifico-Regular.ttf
    - family: Sofia
      fonts:
        - asset: fonts/Sofia-Regular.ttf
    - family: satisfy
      fonts:
        - asset: fonts/satisfy-Regular.ttf
    - family: Gruppo
      fonts:
        - asset: fonts/Gruppo-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
